# Generated by Django 2.2 on 2020-08-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200804_0137'),
        ('posts', '0003_post_content'),
    ]

    operations = [
    ]
