# Generated by Django 2.2 on 2020-08-18 11:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_merge_20200804_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='partida',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
