# Generated by Django 2.2 on 2020-07-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_auto_20200721_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='thumbnail',
        ),
    ]
