# Generated by Django 2.2 on 2020-07-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_remove_player_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Titulo',
        ),
    ]
