# Generated by Django 2.2 on 2020-08-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_delete_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='elo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
